import SwiftUI

// The offline content library. Everything ships in the binary — no network, no accounts.
// Recipes reference ingredients by id; FoodLibrary validates the graph on first access.
enum FoodLibrary {

    // MARK: - Ingredients

    static let ingredients: [Ingredient] = [
        // Vegetables
        Ingredient("onion", "Onion", .vegetables),
        Ingredient("garlic", "Garlic", .vegetables),
        Ingredient("tomato", "Tomato", .vegetables),
        Ingredient("potato", "Potato", .vegetables),
        Ingredient("carrot", "Carrot", .vegetables),
        Ingredient("bell_pepper", "Bell Pepper", .vegetables),
        Ingredient("spinach", "Spinach", .vegetables),
        Ingredient("broccoli", "Broccoli", .vegetables),
        Ingredient("mushroom", "Mushrooms", .vegetables),
        Ingredient("zucchini", "Zucchini", .vegetables),
        Ingredient("cucumber", "Cucumber", .vegetables),
        Ingredient("lettuce", "Lettuce", .vegetables),
        Ingredient("corn", "Corn", .vegetables),
        Ingredient("peas", "Peas", .vegetables),
        Ingredient("green_beans", "Green Beans", .vegetables),
        Ingredient("cabbage", "Cabbage", .vegetables),
        Ingredient("cauliflower", "Cauliflower", .vegetables),
        Ingredient("celery", "Celery", .vegetables),
        Ingredient("sweet_potato", "Sweet Potato", .vegetables),
        Ingredient("scallion", "Scallion", .vegetables),
        Ingredient("eggplant", "Eggplant", .vegetables),

        // Fruits
        Ingredient("lemon", "Lemon", .fruits),
        Ingredient("lime", "Lime", .fruits),
        Ingredient("apple", "Apple", .fruits),
        Ingredient("banana", "Banana", .fruits),
        Ingredient("avocado", "Avocado", .fruits),
        Ingredient("orange", "Orange", .fruits),
        Ingredient("mixed_berries", "Mixed Berries", .fruits),

        // Proteins
        Ingredient("chicken", "Chicken", .proteins),
        Ingredient("beef", "Beef", .proteins),
        Ingredient("ground_beef", "Ground Beef", .proteins),
        Ingredient("pork", "Pork", .proteins),
        Ingredient("bacon", "Bacon", .proteins),
        Ingredient("sausage", "Sausage", .proteins),
        Ingredient("ham", "Ham", .proteins),
        Ingredient("tofu", "Tofu", .proteins),
        Ingredient("chickpeas", "Chickpeas", .proteins),
        Ingredient("black_beans", "Black Beans", .proteins),
        Ingredient("lentils", "Lentils", .proteins),
        Ingredient("kidney_beans", "Kidney Beans", .proteins),
        Ingredient("shrimp", "Shrimp", .proteins),
        Ingredient("salmon", "Salmon", .proteins),
        Ingredient("tuna", "Canned Tuna", .proteins),

        // Dairy & Eggs
        Ingredient("eggs", "Eggs", .dairy),
        Ingredient("milk", "Milk", .dairy),
        Ingredient("butter", "Butter", .dairy),
        Ingredient("cheddar", "Cheddar", .dairy),
        Ingredient("parmesan", "Parmesan", .dairy),
        Ingredient("mozzarella", "Mozzarella", .dairy),
        Ingredient("yogurt", "Yogurt", .dairy),
        Ingredient("heavy_cream", "Heavy Cream", .dairy),
        Ingredient("feta", "Feta", .dairy),

        // Grains & Pasta
        Ingredient("rice", "Rice", .grains),
        Ingredient("pasta", "Pasta", .grains),
        Ingredient("spaghetti", "Spaghetti", .grains),
        Ingredient("bread", "Bread", .grains),
        Ingredient("flour", "Flour", .grains),
        Ingredient("oats", "Oats", .grains),
        Ingredient("tortilla", "Tortilla", .grains),
        Ingredient("noodles", "Noodles", .grains),

        // Pantry Staples
        Ingredient("salt", "Salt", .staples, staple: true),
        Ingredient("black_pepper", "Black Pepper", .staples, staple: true),
        Ingredient("olive_oil", "Olive Oil", .staples, staple: true),
        Ingredient("veg_oil", "Vegetable Oil", .staples, staple: true),
        Ingredient("sugar", "Sugar", .staples, staple: true),
        Ingredient("water", "Water", .staples, staple: true),
        Ingredient("soy_sauce", "Soy Sauce", .staples),
        Ingredient("vinegar", "Vinegar", .staples),
        Ingredient("honey", "Honey", .staples),
        Ingredient("tomato_paste", "Tomato Paste", .staples),
        Ingredient("canned_tomatoes", "Canned Tomatoes", .staples),
        Ingredient("stock", "Stock", .staples),
        Ingredient("coconut_milk", "Coconut Milk", .staples),
        Ingredient("baking_powder", "Baking Powder", .staples),
        Ingredient("mustard", "Mustard", .staples),
        Ingredient("mayo", "Mayonnaise", .staples),
        Ingredient("peanut_butter", "Peanut Butter", .staples),
        Ingredient("curry_powder", "Curry Powder", .staples),
        Ingredient("cumin", "Cumin", .staples),
        Ingredient("paprika", "Paprika", .staples),
        Ingredient("chili_flakes", "Chili Flakes", .staples),

        // Herbs & Spices
        Ingredient("basil", "Basil", .herbs),
        Ingredient("parsley", "Parsley", .herbs),
        Ingredient("cilantro", "Cilantro", .herbs),
        Ingredient("ginger", "Ginger", .herbs),
        Ingredient("cinnamon", "Cinnamon", .herbs),
        Ingredient("oregano", "Oregano", .herbs),
        Ingredient("thyme", "Thyme", .herbs),
        Ingredient("turmeric", "Turmeric", .herbs),
    ]

    // Fast lookups.
    static let byID: [String: Ingredient] = {
        Dictionary(uniqueKeysWithValues: ingredients.map { ($0.id, $0) })
    }()

    static let stapleIDs: Set<String> = {
        Set(ingredients.filter { $0.isStaple }.map { $0.id })
    }()

    static func name(for id: String) -> String { byID[id]?.name ?? id }
    static func ingredient(_ id: String) -> Ingredient? { byID[id] }

    static func grouped() -> [(group: IngredientGroup, items: [Ingredient])] {
        IngredientGroup.allCases.map { g in
            (g, ingredients.filter { $0.group == g })
        }
    }

    // MARK: - Recipes

    static let recipes: [Recipe] = [
        Recipe(id: "tomato_garlic_pasta", name: "Tomato Garlic Pasta",
               blurb: "A weeknight classic that comes together in one pan.",
               kind: .dinner, minutes: 20, servings: 2, difficulty: .easy,
               items: [RecipeItem("pasta", "200 g"), RecipeItem("tomato", "3, chopped"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("basil", "a handful"), RecipeItem("parmesan", "to serve"),
                       RecipeItem("salt", "to taste"), RecipeItem("black_pepper", "to taste")],
               steps: ["Boil the pasta in well-salted water until al dente, then drain and reserve a splash of the cooking water.",
                       "Warm the olive oil in a pan and soften the sliced garlic for a minute without browning.",
                       "Add the chopped tomatoes and a pinch of salt; simmer until they collapse into a light sauce.",
                       "Toss the pasta through the sauce with a little reserved water until glossy.",
                       "Finish with torn basil, black pepper, and grated parmesan."],
               tip: "A splash of the starchy pasta water helps the sauce cling to every strand."),

        Recipe(id: "veggie_fried_rice", name: "Veggie Fried Rice",
               blurb: "The best way to rescue yesterday's rice.",
               kind: .dinner, minutes: 20, servings: 2, difficulty: .easy,
               items: [RecipeItem("rice", "2 cups, cooked"), RecipeItem("eggs", "2"),
                       RecipeItem("carrot", "1, diced"), RecipeItem("peas", "1/2 cup"),
                       RecipeItem("scallion", "2, sliced"), RecipeItem("soy_sauce", "2 tbsp"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("veg_oil", "1 tbsp")],
               steps: ["Heat the oil in a wide pan or wok over high heat.",
                       "Scramble the eggs quickly, then push them to one side.",
                       "Add the garlic, carrot, and peas; stir-fry until just tender.",
                       "Add the cold rice, breaking up any clumps, and fry until piping hot.",
                       "Splash in the soy sauce, toss through the scallions, and serve."],
               tip: "Cold, day-old rice fries up far better than fresh — it stays separate, not mushy."),

        Recipe(id: "classic_omelette", name: "Classic Cheese Omelette",
               blurb: "Three eggs, a hot pan, and two minutes.",
               kind: .breakfast, minutes: 10, servings: 1, difficulty: .easy,
               items: [RecipeItem("eggs", "3"), RecipeItem("butter", "1 tbsp"),
                       RecipeItem("cheddar", "1/3 cup, grated"),
                       RecipeItem("salt", "a pinch"), RecipeItem("black_pepper", "a pinch")],
               steps: ["Beat the eggs with salt and pepper until fully blended.",
                       "Melt the butter in a non-stick pan over medium heat until foaming.",
                       "Pour in the eggs and stir gently, pulling the set edges toward the centre.",
                       "When the top is just barely wet, scatter the cheese over one half.",
                       "Fold and slide onto a plate; the residual heat finishes it."],
               tip: "Take it off the heat while the centre still looks slightly underdone — it keeps cooking on the plate."),

        Recipe(id: "chicken_stir_fry", name: "Chicken Stir Fry",
               blurb: "Fast, colourful, and endlessly adaptable.",
               kind: .dinner, minutes: 25, servings: 2, difficulty: .medium,
               items: [RecipeItem("chicken", "2 breasts, sliced"), RecipeItem("bell_pepper", "1, sliced"),
                       RecipeItem("broccoli", "1 cup florets"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("ginger", "1 tsp, grated"), RecipeItem("soy_sauce", "3 tbsp"),
                       RecipeItem("veg_oil", "1 tbsp"), RecipeItem("rice", "to serve")],
               steps: ["Get the rice cooking so it's ready when the stir-fry is done.",
                       "Sear the sliced chicken in hot oil until golden, then set aside.",
                       "Stir-fry the garlic and ginger for 30 seconds, then add the pepper and broccoli.",
                       "Return the chicken, pour in the soy sauce, and toss until everything is coated and hot.",
                       "Spoon over the rice and serve immediately."],
               tip: "Have everything chopped before you start — stir-frying moves too fast to prep as you go."),

        Recipe(id: "lentil_soup", name: "Hearty Lentil Soup",
               blurb: "Cheap, filling, and better the next day.",
               kind: .soup, minutes: 40, servings: 4, difficulty: .easy,
               items: [RecipeItem("lentils", "1 cup"), RecipeItem("carrot", "2, diced"),
                       RecipeItem("onion", "1, diced"), RecipeItem("celery", "2 stalks"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("canned_tomatoes", "1 can"),
                       RecipeItem("stock", "5 cups"), RecipeItem("cumin", "1 tsp"),
                       RecipeItem("olive_oil", "2 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion, carrot, and celery in olive oil until fragrant.",
                       "Stir in the garlic and cumin and cook for another minute.",
                       "Add the lentils, canned tomatoes, and stock; bring to a boil.",
                       "Simmer for 25–30 minutes until the lentils are soft.",
                       "Season generously with salt and serve."],
               tip: "Blend half the soup for a creamy body while keeping the rest chunky."),

        Recipe(id: "avocado_toast", name: "Avocado Toast",
               blurb: "The five-minute breakfast that actually fills you up.",
               kind: .breakfast, minutes: 8, servings: 1, difficulty: .easy,
               items: [RecipeItem("bread", "2 slices"), RecipeItem("avocado", "1, ripe"),
                       RecipeItem("lemon", "a squeeze"), RecipeItem("chili_flakes", "a pinch"),
                       RecipeItem("salt", "to taste"), RecipeItem("black_pepper", "to taste")],
               steps: ["Toast the bread until deeply golden and crisp.",
                       "Mash the avocado with a squeeze of lemon, salt, and pepper.",
                       "Spread thickly over the toast.",
                       "Finish with a pinch of chili flakes."],
               tip: "An egg on top turns this into a proper meal."),

        Recipe(id: "grilled_cheese", name: "Grilled Cheese Sandwich",
               blurb: "Golden outside, molten inside.",
               kind: .lunch, minutes: 10, servings: 1, difficulty: .easy,
               items: [RecipeItem("bread", "2 slices"), RecipeItem("cheddar", "2 slices or a handful grated"),
                       RecipeItem("butter", "1 tbsp")],
               steps: ["Butter the outer sides of both bread slices.",
                       "Sandwich the cheese between the unbuttered sides.",
                       "Cook in a pan over medium-low heat until golden underneath.",
                       "Flip and press gently until the second side is crisp and the cheese has melted."],
               tip: "Low and slow is the secret — high heat burns the bread before the cheese melts."),

        Recipe(id: "banana_pancakes", name: "Banana Pancakes",
               blurb: "Fluffy stacks from very ripe bananas.",
               kind: .breakfast, minutes: 20, servings: 2, difficulty: .easy,
               items: [RecipeItem("banana", "1, mashed"), RecipeItem("eggs", "1"),
                       RecipeItem("flour", "1 cup"), RecipeItem("milk", "3/4 cup"),
                       RecipeItem("baking_powder", "1 tsp"), RecipeItem("butter", "for the pan"),
                       RecipeItem("sugar", "1 tbsp")],
               steps: ["Whisk together the flour, baking powder, and sugar.",
                       "In another bowl mix the egg, milk, and mashed banana.",
                       "Fold the wet into the dry just until combined — lumps are fine.",
                       "Cook spoonfuls in a buttered pan until bubbles form, then flip.",
                       "Stack and serve warm."],
               tip: "The riper and browner the banana, the sweeter the pancakes."),

        Recipe(id: "caprese_salad", name: "Caprese Salad",
               blurb: "Three good ingredients, nothing to hide behind.",
               kind: .salad, minutes: 10, servings: 2, difficulty: .easy,
               items: [RecipeItem("tomato", "2, ripe"), RecipeItem("mozzarella", "1 ball"),
                       RecipeItem("basil", "a handful"), RecipeItem("olive_oil", "to drizzle"),
                       RecipeItem("salt", "to taste"), RecipeItem("black_pepper", "to taste")],
               steps: ["Slice the tomatoes and mozzarella into rounds.",
                       "Arrange them alternating on a plate with basil leaves tucked between.",
                       "Drizzle generously with olive oil.",
                       "Season with salt and pepper just before serving."],
               tip: "Use the ripest tomatoes you can find — this dish lives or dies by them."),

        Recipe(id: "black_bean_tacos", name: "Black Bean Tacos",
               blurb: "A pantry dinner that feels like a treat.",
               kind: .dinner, minutes: 20, servings: 3, difficulty: .easy,
               items: [RecipeItem("tortilla", "6 small"), RecipeItem("black_beans", "1 can"),
                       RecipeItem("corn", "1/2 cup"), RecipeItem("tomato", "1, diced"),
                       RecipeItem("avocado", "1, sliced"), RecipeItem("cheddar", "grated"),
                       RecipeItem("lime", "1"), RecipeItem("cumin", "1 tsp")],
               steps: ["Warm the drained beans with the cumin and a splash of water until saucy.",
                       "Char the tortillas briefly in a dry pan.",
                       "Fill each with beans, corn, tomato, and avocado.",
                       "Top with cheese and a good squeeze of lime."],
               tip: "Mash some of the beans for a filling that holds together better."),

        Recipe(id: "tomato_soup", name: "Creamy Tomato Soup",
               blurb: "The soup that begs for a grilled cheese.",
               kind: .soup, minutes: 30, servings: 4, difficulty: .easy,
               items: [RecipeItem("canned_tomatoes", "2 cans"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("stock", "2 cups"),
                       RecipeItem("heavy_cream", "1/4 cup"), RecipeItem("basil", "a handful"),
                       RecipeItem("olive_oil", "2 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion and garlic in olive oil.",
                       "Add the canned tomatoes and stock; simmer for 15 minutes.",
                       "Blend until smooth, then stir in the cream.",
                       "Season with salt and finish with torn basil."],
               tip: "A pinch of sugar rounds out any sharpness in the tomatoes."),

        Recipe(id: "chicken_noodle_soup", name: "Chicken Noodle Soup",
               blurb: "The one you make when someone's under the weather.",
               kind: .soup, minutes: 40, servings: 4, difficulty: .medium,
               items: [RecipeItem("chicken", "2 breasts"), RecipeItem("noodles", "2 cups"),
                       RecipeItem("carrot", "2, sliced"), RecipeItem("celery", "2 stalks"),
                       RecipeItem("onion", "1, diced"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("stock", "6 cups"), RecipeItem("parsley", "to serve"),
                       RecipeItem("salt", "to taste")],
               steps: ["Simmer the chicken in the stock with onion, carrot, celery, and garlic until cooked through.",
                       "Lift out the chicken, shred it, and return it to the pot.",
                       "Add the noodles and cook until tender.",
                       "Season with salt and scatter with parsley."],
               tip: "Cook the noodles separately if you plan to save leftovers — they turn soft in stored soup."),

        Recipe(id: "beef_chili", name: "Beef Chili",
               blurb: "A big pot of comfort for a cold night.",
               kind: .dinner, minutes: 45, servings: 4, difficulty: .medium,
               items: [RecipeItem("ground_beef", "500 g"), RecipeItem("kidney_beans", "1 can"),
                       RecipeItem("canned_tomatoes", "1 can"), RecipeItem("onion", "1, diced"),
                       RecipeItem("bell_pepper", "1, diced"), RecipeItem("garlic", "3 cloves"),
                       RecipeItem("cumin", "1 tsp"), RecipeItem("paprika", "1 tsp"),
                       RecipeItem("chili_flakes", "to taste"), RecipeItem("salt", "to taste")],
               steps: ["Brown the beef in a large pot, breaking it up as it cooks.",
                       "Add the onion, pepper, and garlic; cook until soft.",
                       "Stir in the spices, then the tomatoes and drained beans.",
                       "Simmer for 25–30 minutes until thick.",
                       "Taste and adjust the salt and chili."],
               tip: "It tastes even better reheated the next day once the flavours settle."),

        Recipe(id: "spaghetti_bolognese", name: "Spaghetti Bolognese",
               blurb: "A slow-simmered ragù over a nest of spaghetti.",
               kind: .dinner, minutes: 45, servings: 4, difficulty: .medium,
               items: [RecipeItem("spaghetti", "400 g"), RecipeItem("ground_beef", "500 g"),
                       RecipeItem("canned_tomatoes", "1 can"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("carrot", "1, grated"),
                       RecipeItem("tomato_paste", "2 tbsp"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("parmesan", "to serve"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion, carrot, and garlic in olive oil.",
                       "Add the beef and brown well.",
                       "Stir in the tomato paste, then the canned tomatoes.",
                       "Simmer gently for at least 30 minutes, adding a little water if it dries out.",
                       "Serve over spaghetti with grated parmesan."],
               tip: "Grated carrot melts into the sauce and adds a gentle natural sweetness."),

        Recipe(id: "greek_salad", name: "Greek Salad",
               blurb: "Crisp, bright, and no cooking required.",
               kind: .salad, minutes: 12, servings: 2, difficulty: .easy,
               items: [RecipeItem("cucumber", "1"), RecipeItem("tomato", "2"),
                       RecipeItem("onion", "1/2, thin sliced"), RecipeItem("olive_oil", "3 tbsp"),
                       RecipeItem("lemon", "1/2"), RecipeItem("oregano", "1 tsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Chop the cucumber and tomatoes into big chunks.",
                       "Add the thinly sliced onion.",
                       "Dress with olive oil, lemon juice, oregano, and salt.",
                       "Toss and let it sit a few minutes before serving."],
               tip: "Salt the tomatoes first and let them weep — it builds a natural dressing."),

        Recipe(id: "scrambled_eggs", name: "Fluffy Scrambled Eggs",
               blurb: "Soft, custardy curds done right.",
               kind: .breakfast, minutes: 8, servings: 1, difficulty: .easy,
               items: [RecipeItem("eggs", "3"), RecipeItem("butter", "1 tbsp"),
                       RecipeItem("milk", "1 tbsp"), RecipeItem("salt", "a pinch"),
                       RecipeItem("black_pepper", "a pinch")],
               steps: ["Beat the eggs with the milk, salt, and pepper.",
                       "Melt the butter in a pan over low heat.",
                       "Add the eggs and stir slowly and constantly.",
                       "Pull them off the heat while still glossy and slightly wet."],
               tip: "Low heat and patience are everything — rushing gives you rubber."),

        Recipe(id: "mashed_potatoes", name: "Buttery Mashed Potatoes",
               blurb: "Cloud-soft and rich.",
               kind: .dinner, minutes: 30, servings: 4, difficulty: .easy,
               items: [RecipeItem("potato", "800 g"), RecipeItem("butter", "3 tbsp"),
                       RecipeItem("milk", "1/2 cup, warm"), RecipeItem("salt", "to taste"),
                       RecipeItem("black_pepper", "to taste")],
               steps: ["Peel and cube the potatoes, then boil in salted water until fork-tender.",
                       "Drain well and let them steam-dry for a minute.",
                       "Mash with the butter, then beat in the warm milk.",
                       "Season with salt and pepper."],
               tip: "Warm the milk before adding it — cold milk makes the mash gluey and dense."),

        Recipe(id: "chickpea_curry", name: "Chickpea Curry",
               blurb: "A fragrant vegetarian curry from the pantry.",
               kind: .dinner, minutes: 30, servings: 3, difficulty: .medium,
               items: [RecipeItem("chickpeas", "2 cans"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("ginger", "1 tbsp"),
                       RecipeItem("canned_tomatoes", "1 can"), RecipeItem("coconut_milk", "1 can"),
                       RecipeItem("curry_powder", "2 tbsp"), RecipeItem("rice", "to serve"),
                       RecipeItem("veg_oil", "1 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion in oil, then add the garlic and ginger.",
                       "Stir in the curry powder and toast for a minute until fragrant.",
                       "Add the tomatoes, chickpeas, and coconut milk.",
                       "Simmer for 15–20 minutes until thick and creamy.",
                       "Serve over rice."],
               tip: "Toasting the spices in oil before adding liquid wakes up their flavour."),

        Recipe(id: "tuna_melt", name: "Tuna Melt",
               blurb: "Crisp, cheesy, and ready in minutes.",
               kind: .lunch, minutes: 15, servings: 2, difficulty: .easy,
               items: [RecipeItem("tuna", "1 can"), RecipeItem("bread", "4 slices"),
                       RecipeItem("cheddar", "4 slices"), RecipeItem("mayo", "2 tbsp"),
                       RecipeItem("onion", "2 tbsp, minced"), RecipeItem("butter", "for the pan")],
               steps: ["Mix the drained tuna with mayo and minced onion.",
                       "Spread over two slices of bread and top with cheese.",
                       "Close the sandwiches and butter the outsides.",
                       "Grill in a pan until golden and the cheese has melted."],
               tip: "A little mustard stirred into the tuna adds a welcome tang."),

        Recipe(id: "oatmeal_bowl", name: "Warm Oatmeal Bowl",
               blurb: "A cosy bowl to start the day.",
               kind: .breakfast, minutes: 10, servings: 1, difficulty: .easy,
               items: [RecipeItem("oats", "1/2 cup"), RecipeItem("milk", "1 cup"),
                       RecipeItem("banana", "1, sliced"), RecipeItem("honey", "1 tbsp"),
                       RecipeItem("cinnamon", "a pinch")],
               steps: ["Simmer the oats in the milk, stirring, until creamy.",
                       "Pour into a bowl.",
                       "Top with sliced banana, a drizzle of honey, and a dusting of cinnamon."],
               tip: "A pinch of salt in the pot makes the oats taste far less flat."),

        Recipe(id: "veggie_frittata", name: "Vegetable Frittata",
               blurb: "Brunch for a crowd from a single pan.",
               kind: .breakfast, minutes: 25, servings: 3, difficulty: .medium,
               items: [RecipeItem("eggs", "6"), RecipeItem("spinach", "2 cups"),
                       RecipeItem("tomato", "1, diced"), RecipeItem("onion", "1/2, diced"),
                       RecipeItem("cheddar", "1/2 cup"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("salt", "to taste"), RecipeItem("black_pepper", "to taste")],
               steps: ["Soften the onion in an oven-safe pan, then wilt the spinach.",
                       "Beat the eggs with salt, pepper, and half the cheese.",
                       "Pour over the vegetables and scatter the tomato and remaining cheese on top.",
                       "Cook gently until the edges set, then finish under a hot grill until puffed and golden."],
               tip: "No oven-safe pan? Cover with a lid and cook low until the top just sets."),

        Recipe(id: "shrimp_garlic_pasta", name: "Garlic Shrimp Pasta",
               blurb: "Restaurant-feeling dinner in 25 minutes.",
               kind: .dinner, minutes: 25, servings: 2, difficulty: .medium,
               items: [RecipeItem("shrimp", "250 g"), RecipeItem("spaghetti", "200 g"),
                       RecipeItem("garlic", "4 cloves"), RecipeItem("butter", "2 tbsp"),
                       RecipeItem("lemon", "1/2"), RecipeItem("parsley", "a handful"),
                       RecipeItem("chili_flakes", "a pinch"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Cook the spaghetti until al dente and reserve a little pasta water.",
                       "Sizzle the garlic and chili flakes in butter and oil.",
                       "Add the shrimp and cook just until pink.",
                       "Toss in the pasta with a splash of pasta water and a squeeze of lemon.",
                       "Finish with parsley and salt."],
               tip: "Shrimp cook in about two minutes — pull them as soon as they curl and turn pink."),

        Recipe(id: "baked_salmon", name: "Baked Lemon Salmon",
               blurb: "A clean, foolproof dinner.",
               kind: .dinner, minutes: 25, servings: 2, difficulty: .easy,
               items: [RecipeItem("salmon", "2 fillets"), RecipeItem("lemon", "1"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("black_pepper", "to taste"), RecipeItem("salt", "to taste")],
               steps: ["Heat the oven to 200°C (400°F).",
                       "Place the salmon on a lined tray and rub with olive oil, crushed garlic, salt, and pepper.",
                       "Lay lemon slices over the top.",
                       "Bake for 12–15 minutes until the fish flakes easily."],
               tip: "Salmon keeps cooking after it leaves the oven, so take it out just before it looks done."),

        Recipe(id: "potato_hash", name: "Crispy Potato Hash",
               blurb: "Golden, craggy potatoes for a lazy morning.",
               kind: .breakfast, minutes: 25, servings: 2, difficulty: .easy,
               items: [RecipeItem("potato", "3, diced"), RecipeItem("onion", "1, diced"),
                       RecipeItem("bell_pepper", "1, diced"), RecipeItem("veg_oil", "2 tbsp"),
                       RecipeItem("paprika", "1 tsp"), RecipeItem("salt", "to taste")],
               steps: ["Parboil the diced potatoes for 5 minutes, then drain well.",
                       "Fry them in hot oil, undisturbed, until a crust forms.",
                       "Add the onion and pepper and cook until soft and browned.",
                       "Season with paprika and salt."],
               tip: "Resist stirring too often — the crust only forms when the potatoes sit still."),

        Recipe(id: "peanut_noodles", name: "Peanut Butter Noodles",
               blurb: "Creamy, salty, ready before takeout would arrive.",
               kind: .lunch, minutes: 20, servings: 2, difficulty: .easy,
               items: [RecipeItem("noodles", "200 g"), RecipeItem("peanut_butter", "3 tbsp"),
                       RecipeItem("soy_sauce", "2 tbsp"), RecipeItem("garlic", "1 clove"),
                       RecipeItem("ginger", "1 tsp"), RecipeItem("lime", "1/2"),
                       RecipeItem("honey", "1 tsp"), RecipeItem("scallion", "to serve")],
               steps: ["Cook the noodles and reserve a little of the water.",
                       "Whisk the peanut butter, soy sauce, garlic, ginger, lime, and honey into a sauce.",
                       "Loosen with a splash of noodle water until pourable.",
                       "Toss with the noodles and top with scallions."],
               tip: "Warm noodle water melts the peanut butter into a silky sauce instantly."),

        Recipe(id: "chicken_rice_bowl", name: "Chicken Rice Bowl",
               blurb: "A balanced bowl you'll come back to.",
               kind: .lunch, minutes: 30, servings: 2, difficulty: .medium,
               items: [RecipeItem("chicken", "2 breasts"), RecipeItem("rice", "1 cup"),
                       RecipeItem("broccoli", "1 cup"), RecipeItem("carrot", "1, ribboned"),
                       RecipeItem("soy_sauce", "2 tbsp"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("veg_oil", "1 tbsp")],
               steps: ["Cook the rice.",
                       "Steam the broccoli and carrot until just tender.",
                       "Pan-fry the chicken in oil with garlic until golden and cooked through, then slice.",
                       "Build bowls with rice, vegetables, and chicken; drizzle with soy sauce."],
               tip: "Slice the chicken across the grain so every bite stays tender."),

        Recipe(id: "berry_smoothie", name: "Berry Smoothie",
               blurb: "A cold, fruity two-minute breakfast.",
               kind: .drink, minutes: 5, servings: 2, difficulty: .easy,
               items: [RecipeItem("mixed_berries", "1 cup"), RecipeItem("banana", "1"),
                       RecipeItem("yogurt", "1/2 cup"), RecipeItem("milk", "1 cup"),
                       RecipeItem("honey", "1 tsp")],
               steps: ["Add everything to a blender.",
                       "Blend until completely smooth.",
                       "Taste and add a little more honey if needed."],
               tip: "Frozen berries make it thick and frosty with no need for ice."),

        Recipe(id: "cheese_quesadilla", name: "Cheese Quesadilla",
               blurb: "The fastest melty snack there is.",
               kind: .snack, minutes: 12, servings: 1, difficulty: .easy,
               items: [RecipeItem("tortilla", "2"), RecipeItem("cheddar", "1/2 cup"),
                       RecipeItem("mozzarella", "1/2 cup"), RecipeItem("butter", "for the pan")],
               steps: ["Scatter both cheeses over one tortilla and top with the second.",
                       "Cook in a lightly buttered pan until golden underneath.",
                       "Flip carefully and crisp the other side.",
                       "Cut into wedges and serve hot."],
               tip: "Let it rest a minute before cutting so the cheese sets slightly and doesn't spill."),

        Recipe(id: "minestrone", name: "Vegetable Minestrone",
               blurb: "A big, brothy bowl of everything good.",
               kind: .soup, minutes: 40, servings: 4, difficulty: .medium,
               items: [RecipeItem("pasta", "1 cup small"), RecipeItem("canned_tomatoes", "1 can"),
                       RecipeItem("kidney_beans", "1 can"), RecipeItem("carrot", "1, diced"),
                       RecipeItem("celery", "2 stalks"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("zucchini", "1, diced"),
                       RecipeItem("stock", "5 cups"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Soften the onion, carrot, and celery in olive oil.",
                       "Add the garlic, then the tomatoes and stock.",
                       "Simmer 15 minutes, then add the zucchini, beans, and pasta.",
                       "Cook until the pasta is tender and season with salt."],
               tip: "Add the pasta near the end so it doesn't overcook and turn mushy."),

        Recipe(id: "stuffed_peppers", name: "Stuffed Bell Peppers",
               blurb: "Peppers packed with a savoury rice filling.",
               kind: .dinner, minutes: 50, servings: 4, difficulty: .medium,
               items: [RecipeItem("bell_pepper", "4"), RecipeItem("rice", "1 cup, cooked"),
                       RecipeItem("ground_beef", "300 g"), RecipeItem("canned_tomatoes", "1 cup"),
                       RecipeItem("onion", "1, diced"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("cheddar", "1/2 cup"), RecipeItem("cumin", "1 tsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Heat the oven to 190°C (375°F) and halve and seed the peppers.",
                       "Brown the beef with onion and garlic, then stir in the rice, tomatoes, and cumin.",
                       "Spoon the filling into the peppers and top with cheese.",
                       "Bake for 25–30 minutes until the peppers are tender."],
               tip: "Pre-cooked or leftover rice makes the filling come together in minutes."),

        Recipe(id: "banana_bread", name: "Simple Banana Bread",
               blurb: "The reason to let bananas go brown.",
               kind: .dessert, minutes: 60, servings: 8, difficulty: .medium,
               items: [RecipeItem("banana", "3, very ripe"), RecipeItem("flour", "1.5 cups"),
                       RecipeItem("eggs", "2"), RecipeItem("butter", "1/3 cup, melted"),
                       RecipeItem("sugar", "3/4 cup"), RecipeItem("baking_powder", "1 tsp"),
                       RecipeItem("cinnamon", "1 tsp")],
               steps: ["Heat the oven to 175°C (350°F) and line a loaf tin.",
                       "Mash the bananas, then mix in the melted butter, sugar, and eggs.",
                       "Fold in the flour, baking powder, and cinnamon until just combined.",
                       "Pour into the tin and bake 45–55 minutes until a skewer comes out clean."],
               tip: "Don't overmix once the flour is in, or the loaf turns tough and dense."),

        Recipe(id: "guacamole", name: "Fresh Guacamole",
               blurb: "Bright, chunky, and gone in minutes.",
               kind: .snack, minutes: 10, servings: 3, difficulty: .easy,
               items: [RecipeItem("avocado", "2, ripe"), RecipeItem("lime", "1"),
                       RecipeItem("onion", "2 tbsp, minced"), RecipeItem("tomato", "1, diced"),
                       RecipeItem("cilantro", "a handful"), RecipeItem("salt", "to taste")],
               steps: ["Mash the avocado to your preferred texture.",
                       "Stir in the lime juice and salt.",
                       "Fold through the onion, tomato, and chopped cilantro.",
                       "Taste and add more lime or salt as needed."],
               tip: "Press plastic wrap right onto the surface to keep it green if made ahead."),

        Recipe(id: "cucumber_salad", name: "Crunchy Cucumber Salad",
               blurb: "Cool, tangy, and ready in ten minutes.",
               kind: .salad, minutes: 10, servings: 2, difficulty: .easy,
               items: [RecipeItem("cucumber", "2"), RecipeItem("vinegar", "3 tbsp"),
                       RecipeItem("sugar", "1 tbsp"), RecipeItem("scallion", "2, sliced"),
                       RecipeItem("chili_flakes", "a pinch"), RecipeItem("salt", "to taste")],
               steps: ["Thinly slice the cucumbers and salt them; let sit 5 minutes and pat dry.",
                       "Whisk the vinegar with the sugar until dissolved.",
                       "Toss the cucumbers with the dressing, scallions, and chili flakes."],
               tip: "Salting and draining the cucumbers keeps the salad crisp instead of watery."),

        Recipe(id: "french_toast", name: "Golden French Toast",
               blurb: "A weekend breakfast worth waking up for.",
               kind: .breakfast, minutes: 15, servings: 2, difficulty: .easy,
               items: [RecipeItem("bread", "4 slices"), RecipeItem("eggs", "2"),
                       RecipeItem("milk", "1/2 cup"), RecipeItem("cinnamon", "1/2 tsp"),
                       RecipeItem("butter", "for the pan"), RecipeItem("sugar", "1 tbsp")],
               steps: ["Whisk the eggs, milk, cinnamon, and sugar in a shallow dish.",
                       "Soak each slice of bread briefly on both sides.",
                       "Fry in butter over medium heat until golden.",
                       "Serve warm."],
               tip: "Slightly stale bread soaks up the custard without falling apart."),

        Recipe(id: "garden_veg_soup", name: "Garden Vegetable Soup",
               blurb: "Clean out the crisper drawer, deliciously.",
               kind: .soup, minutes: 35, servings: 4, difficulty: .easy,
               items: [RecipeItem("carrot", "2, diced"), RecipeItem("potato", "2, diced"),
                       RecipeItem("celery", "2 stalks"), RecipeItem("onion", "1, diced"),
                       RecipeItem("green_beans", "1 cup"), RecipeItem("canned_tomatoes", "1 can"),
                       RecipeItem("stock", "5 cups"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("olive_oil", "2 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion, carrot, and celery in olive oil.",
                       "Add the garlic, then the potatoes, tomatoes, and stock.",
                       "Simmer 15 minutes, then add the green beans and cook until tender.",
                       "Season with salt to taste."],
               tip: "Almost any vegetable works here — treat the recipe as a template."),

        Recipe(id: "bacon_egg_sandwich", name: "Bacon & Egg Sandwich",
               blurb: "The breakfast sandwich, done at home.",
               kind: .breakfast, minutes: 15, servings: 1, difficulty: .easy,
               items: [RecipeItem("bread", "2 slices"), RecipeItem("eggs", "1"),
                       RecipeItem("bacon", "2 rashers"), RecipeItem("cheddar", "1 slice"),
                       RecipeItem("butter", "for the pan")],
               steps: ["Fry the bacon until crisp, then set aside.",
                       "Fry the egg to your liking in the same pan.",
                       "Toast or butter the bread and add the cheese while everything's hot.",
                       "Stack the bacon and egg, close, and press gently."],
               tip: "Lay the cheese on the hot egg so it melts before you close the sandwich."),

        Recipe(id: "mushroom_rice", name: "Creamy Mushroom Rice",
               blurb: "A comforting one-pan side or light dinner.",
               kind: .dinner, minutes: 30, servings: 3, difficulty: .medium,
               items: [RecipeItem("rice", "1 cup"), RecipeItem("mushroom", "300 g"),
                       RecipeItem("onion", "1, diced"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("parmesan", "1/3 cup"), RecipeItem("butter", "2 tbsp"),
                       RecipeItem("stock", "2.5 cups"), RecipeItem("olive_oil", "1 tbsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Brown the mushrooms in butter and oil until deeply golden, then set aside.",
                       "Soften the onion and garlic in the same pan.",
                       "Stir in the rice, then add the stock a little at a time, stirring often.",
                       "When the rice is tender, fold the mushrooms and parmesan back in and season."],
               tip: "Give the mushrooms room in the pan so they brown instead of steam."),

        Recipe(id: "apple_crumble", name: "Apple Cinnamon Crumble",
               blurb: "Warm spiced apples under a buttery lid.",
               kind: .dessert, minutes: 45, servings: 4, difficulty: .medium,
               items: [RecipeItem("apple", "4, peeled and sliced"), RecipeItem("flour", "3/4 cup"),
                       RecipeItem("butter", "1/3 cup, cold"), RecipeItem("sugar", "1/2 cup"),
                       RecipeItem("oats", "1/2 cup"), RecipeItem("cinnamon", "1 tsp")],
               steps: ["Heat the oven to 180°C (350°F) and toss the apples with half the sugar and the cinnamon.",
                       "Rub the cold butter into the flour, oats, and remaining sugar until crumbly.",
                       "Spread the apples in a dish and cover with the crumble.",
                       "Bake for 30–35 minutes until golden and bubbling."],
               tip: "A squeeze of lemon over the apples keeps the filling from tasting flat."),

        Recipe(id: "coleslaw", name: "Creamy Coleslaw",
               blurb: "The crunchy side every barbecue needs.",
               kind: .salad, minutes: 15, servings: 4, difficulty: .easy,
               items: [RecipeItem("cabbage", "1/2, shredded"), RecipeItem("carrot", "2, grated"),
                       RecipeItem("mayo", "1/3 cup"), RecipeItem("vinegar", "1 tbsp"),
                       RecipeItem("sugar", "1 tsp"), RecipeItem("salt", "to taste")],
               steps: ["Shred the cabbage and grate the carrot into a big bowl.",
                       "Whisk the mayo, vinegar, sugar, and salt into a dressing.",
                       "Toss everything together.",
                       "Chill for 20 minutes before serving for the best texture."],
               tip: "Let it rest in the fridge — the flavour and crunch both improve as it sits."),

        Recipe(id: "tofu_stir_fry", name: "Sesame Tofu Stir Fry",
               blurb: "Crisp tofu and crunchy veg in a glossy sauce.",
               kind: .dinner, minutes: 25, servings: 2, difficulty: .medium,
               items: [RecipeItem("tofu", "1 block"), RecipeItem("broccoli", "1 cup"),
                       RecipeItem("bell_pepper", "1, sliced"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("ginger", "1 tsp"), RecipeItem("soy_sauce", "3 tbsp"),
                       RecipeItem("veg_oil", "2 tbsp"), RecipeItem("rice", "to serve")],
               steps: ["Press and cube the tofu, then fry in oil until golden on all sides.",
                       "Remove the tofu and stir-fry the garlic, ginger, pepper, and broccoli.",
                       "Return the tofu, add the soy sauce, and toss until coated.",
                       "Serve over rice."],
               tip: "Pressing the tofu first drives out water so it crisps instead of steaming."),

        Recipe(id: "sausage_pasta", name: "Sausage Tomato Pasta",
               blurb: "Big flavour from a handful of ingredients.",
               kind: .dinner, minutes: 25, servings: 3, difficulty: .easy,
               items: [RecipeItem("pasta", "300 g"), RecipeItem("sausage", "4, casings removed"),
                       RecipeItem("canned_tomatoes", "1 can"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("olive_oil", "1 tbsp"),
                       RecipeItem("parmesan", "to serve"), RecipeItem("chili_flakes", "a pinch"),
                       RecipeItem("salt", "to taste")],
               steps: ["Cook the pasta until al dente.",
                       "Brown the crumbled sausage in olive oil.",
                       "Add the onion, garlic, and chili flakes; cook until soft.",
                       "Stir in the tomatoes and simmer 10 minutes, then toss with the pasta and parmesan."],
               tip: "Squeezing sausage out of its casing gives you instant seasoned mince."),

        Recipe(id: "ham_cheese_melt", name: "Ham & Cheese Melt",
               blurb: "A hot, gooey lunch in ten minutes.",
               kind: .lunch, minutes: 10, servings: 1, difficulty: .easy,
               items: [RecipeItem("bread", "2 slices"), RecipeItem("ham", "2 slices"),
                       RecipeItem("cheddar", "2 slices"), RecipeItem("butter", "1 tbsp"),
                       RecipeItem("mustard", "1 tsp")],
               steps: ["Spread a little mustard on the bread.",
                       "Layer the ham and cheese between the slices.",
                       "Butter the outsides and grill in a pan until golden and melted."],
               tip: "A thin smear of mustard cuts the richness and lifts the whole sandwich."),

        Recipe(id: "beef_stew", name: "Rustic Beef Stew",
               blurb: "Slow-cooked and worth every minute.",
               kind: .dinner, minutes: 90, servings: 4, difficulty: .medium,
               items: [RecipeItem("beef", "600 g, cubed"), RecipeItem("potato", "3, chunked"),
                       RecipeItem("carrot", "3, chunked"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("canned_tomatoes", "1 can"),
                       RecipeItem("stock", "3 cups"), RecipeItem("thyme", "1 tsp"),
                       RecipeItem("olive_oil", "2 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Brown the beef in batches in olive oil, then set aside.",
                       "Soften the onion and garlic in the same pot.",
                       "Return the beef with the tomatoes, stock, and thyme; bring to a simmer.",
                       "Cook gently for an hour, then add the potato and carrot and simmer until tender.",
                       "Season with salt."],
               tip: "Brown the beef hard and in batches — crowding the pot steams it grey."),

        Recipe(id: "garden_wrap", name: "Garden Veggie Wrap",
               blurb: "A fresh, no-cook lunch you can build in minutes.",
               kind: .lunch, minutes: 12, servings: 1, difficulty: .easy,
               items: [RecipeItem("tortilla", "1 large"), RecipeItem("lettuce", "a handful"),
                       RecipeItem("tomato", "1, sliced"), RecipeItem("cucumber", "1/2, sliced"),
                       RecipeItem("avocado", "1/2, mashed"), RecipeItem("cheddar", "grated"),
                       RecipeItem("mayo", "1 tbsp")],
               steps: ["Spread the mashed avocado and mayo over the tortilla.",
                       "Layer the lettuce, tomato, cucumber, and cheese down the middle.",
                       "Fold in the sides and roll up tightly.",
                       "Slice in half to serve."],
               tip: "Keep the filling off the very edges so the wrap seals without spilling."),

        Recipe(id: "roast_veggies", name: "Roasted Root Vegetables",
               blurb: "Caramelised, crispy-edged, deeply savoury.",
               kind: .dinner, minutes: 40, servings: 4, difficulty: .easy,
               items: [RecipeItem("sweet_potato", "1, chunked"), RecipeItem("potato", "2, chunked"),
                       RecipeItem("carrot", "3, chunked"), RecipeItem("cauliflower", "1/2 head"),
                       RecipeItem("olive_oil", "3 tbsp"), RecipeItem("paprika", "1 tsp"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("salt", "to taste")],
               steps: ["Heat the oven to 210°C (410°F).",
                       "Toss all the vegetables with olive oil, paprika, crushed garlic, and salt.",
                       "Spread in a single layer on a tray.",
                       "Roast 30–35 minutes, turning once, until golden and tender."],
               tip: "Don't crowd the tray — vegetables need space to roast rather than steam."),

        Recipe(id: "honey_garlic_pork", name: "Honey Garlic Pork",
               blurb: "Sticky, sweet, and salty over rice.",
               kind: .dinner, minutes: 30, servings: 3, difficulty: .medium,
               items: [RecipeItem("pork", "500 g, cubed"), RecipeItem("garlic", "4 cloves"),
                       RecipeItem("honey", "3 tbsp"), RecipeItem("soy_sauce", "3 tbsp"),
                       RecipeItem("ginger", "1 tsp"), RecipeItem("veg_oil", "1 tbsp"),
                       RecipeItem("rice", "to serve")],
               steps: ["Sear the pork in hot oil until browned on all sides.",
                       "Add the garlic and ginger and cook for a minute.",
                       "Pour in the honey and soy sauce and let it bubble into a glaze.",
                       "Toss the pork until sticky and serve over rice."],
               tip: "Let the sauce reduce until it coats the back of a spoon for maximum stickiness."),

        Recipe(id: "citrus_fruit_salad", name: "Citrus Fruit Salad",
               blurb: "A bright, refreshing bowl with no cooking at all.",
               kind: .snack, minutes: 10, servings: 2, difficulty: .easy,
               items: [RecipeItem("orange", "2, segmented"), RecipeItem("apple", "1, diced"),
                       RecipeItem("banana", "1, sliced"), RecipeItem("mixed_berries", "1 cup"),
                       RecipeItem("honey", "1 tbsp"), RecipeItem("lime", "1/2")],
               steps: ["Combine all the prepared fruit in a bowl.",
                       "Whisk the honey with the lime juice.",
                       "Drizzle over the fruit and toss gently.",
                       "Chill briefly before serving."],
               tip: "The lime keeps the apple and banana from browning while it sits."),

        Recipe(id: "shakshuka", name: "Skillet Shakshuka",
               blurb: "Eggs poached in a smoky pepper-tomato sauce.",
               kind: .breakfast, minutes: 25, servings: 2, difficulty: .medium,
               items: [RecipeItem("eggs", "4"), RecipeItem("canned_tomatoes", "1 can"),
                       RecipeItem("bell_pepper", "1, sliced"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("cumin", "1 tsp"),
                       RecipeItem("paprika", "1 tsp"), RecipeItem("olive_oil", "2 tbsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Soften the onion and pepper in olive oil until sweet and floppy.",
                       "Add the garlic, cumin, and paprika and cook for a minute.",
                       "Pour in the tomatoes and simmer into a thick sauce.",
                       "Make four wells and crack an egg into each.",
                       "Cover and cook gently until the whites set but the yolks stay soft."],
               tip: "Serve straight from the pan with bread for mopping up the sauce."),

        Recipe(id: "ratatouille", name: "Rustic Ratatouille",
               blurb: "Provence in a pot — summer vegetables stewed slowly.",
               kind: .dinner, minutes: 45, servings: 4, difficulty: .medium,
               items: [RecipeItem("eggplant", "1, cubed"), RecipeItem("zucchini", "1, sliced"),
                       RecipeItem("bell_pepper", "1, sliced"), RecipeItem("tomato", "3, chopped"),
                       RecipeItem("onion", "1, diced"), RecipeItem("garlic", "3 cloves"),
                       RecipeItem("thyme", "1 tsp"), RecipeItem("olive_oil", "3 tbsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Brown the eggplant in half the oil and set aside.",
                       "Soften the onion, pepper, and garlic in the rest of the oil.",
                       "Add the zucchini, tomatoes, thyme, and the eggplant.",
                       "Simmer gently, partly covered, for 25 minutes.",
                       "Season and rest 10 minutes before serving — it improves as it sits."],
               tip: "Browning the eggplant first keeps it silky instead of soggy."),

        Recipe(id: "golden_lentil_dal", name: "Golden Lentil Dal",
               blurb: "Creamy spiced lentils, gentle heat, big comfort.",
               kind: .dinner, minutes: 35, servings: 4, difficulty: .easy,
               items: [RecipeItem("lentils", "1 cup"), RecipeItem("onion", "1, diced"),
                       RecipeItem("garlic", "3 cloves"), RecipeItem("ginger", "1 tbsp"),
                       RecipeItem("turmeric", "1 tsp"), RecipeItem("cumin", "1 tsp"),
                       RecipeItem("coconut_milk", "1 cup"), RecipeItem("rice", "to serve"),
                       RecipeItem("veg_oil", "1 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion in oil, then add the garlic, ginger, turmeric, and cumin.",
                       "Add the lentils and 3 cups of water; simmer 20 minutes until soft.",
                       "Stir in the coconut milk and cook 5 more minutes.",
                       "Season well and serve over rice."],
               tip: "Dal thickens as it stands — loosen leftovers with a splash of water."),

        Recipe(id: "spiced_potato_curry", name: "Spiced Potato Curry",
               blurb: "A cozy potato-and-pea curry from pantry basics.",
               kind: .dinner, minutes: 30, servings: 3, difficulty: .easy,
               items: [RecipeItem("potato", "4, cubed"), RecipeItem("peas", "1 cup"),
                       RecipeItem("onion", "1, diced"), RecipeItem("tomato", "2, chopped"),
                       RecipeItem("curry_powder", "2 tbsp"), RecipeItem("ginger", "1 tsp"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("veg_oil", "2 tbsp"),
                       RecipeItem("cilantro", "to serve"), RecipeItem("salt", "to taste")],
               steps: ["Fry the onion until golden, then add the garlic, ginger, and curry powder.",
                       "Add the tomatoes and cook down into a paste.",
                       "Add the potatoes and enough water to almost cover; simmer until tender.",
                       "Stir in the peas for the last few minutes.",
                       "Finish with salt and fresh cilantro."],
               tip: "Let the tomatoes really cook down — that's where the depth comes from."),

        Recipe(id: "coconut_veggie_curry", name: "Coconut Veggie Curry",
               blurb: "Cauliflower and peas in a silky coconut sauce.",
               kind: .dinner, minutes: 30, servings: 3, difficulty: .easy,
               items: [RecipeItem("cauliflower", "1/2 head"), RecipeItem("peas", "1 cup"),
                       RecipeItem("coconut_milk", "1 can"), RecipeItem("curry_powder", "2 tbsp"),
                       RecipeItem("tomato", "2, chopped"), RecipeItem("ginger", "1 tbsp"),
                       RecipeItem("onion", "1, diced"), RecipeItem("rice", "to serve"),
                       RecipeItem("veg_oil", "1 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Soften the onion, then add the ginger and curry powder.",
                       "Add the tomatoes and coconut milk and bring to a simmer.",
                       "Add the cauliflower and cook until just tender.",
                       "Stir in the peas, season, and serve over rice."],
               tip: "Don't boil coconut milk hard — a gentle simmer keeps it silky."),

        Recipe(id: "teriyaki_chicken", name: "Teriyaki Glazed Chicken",
               blurb: "Sweet-savory glaze, sticky and glossy.",
               kind: .dinner, minutes: 25, servings: 2, difficulty: .easy,
               items: [RecipeItem("chicken", "2 breasts, sliced"), RecipeItem("soy_sauce", "4 tbsp"),
                       RecipeItem("honey", "2 tbsp"), RecipeItem("ginger", "1 tsp"),
                       RecipeItem("garlic", "2 cloves"), RecipeItem("rice", "to serve"),
                       RecipeItem("scallion", "to serve"), RecipeItem("veg_oil", "1 tbsp")],
               steps: ["Sear the chicken in hot oil until golden.",
                       "Add the garlic and ginger and cook for a minute.",
                       "Pour in the soy sauce and honey and let it bubble to a glaze.",
                       "Toss to coat, then serve over rice with scallions."],
               tip: "Pull the glaze off the heat as soon as it coats a spoon — it keeps thickening."),

        Recipe(id: "soy_ginger_noodles", name: "Soy Ginger Noodles",
               blurb: "A 15-minute noodle bowl with punchy aromatics.",
               kind: .lunch, minutes: 15, servings: 2, difficulty: .easy,
               items: [RecipeItem("noodles", "200 g"), RecipeItem("scallion", "3, sliced"),
                       RecipeItem("ginger", "1 tbsp"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("soy_sauce", "3 tbsp"), RecipeItem("honey", "1 tsp"),
                       RecipeItem("veg_oil", "2 tbsp")],
               steps: ["Cook the noodles and drain.",
                       "Sizzle the ginger, garlic, and most of the scallions in hot oil.",
                       "Add the soy sauce and honey, then toss in the noodles.",
                       "Top with the remaining scallions."],
               tip: "Pour the hot oil mixture over the noodles for an instant sauce."),

        Recipe(id: "egg_drop_soup", name: "Silky Egg Drop Soup",
               blurb: "Golden ribbons in a gingery broth, done in 15.",
               kind: .soup, minutes: 15, servings: 2, difficulty: .easy,
               items: [RecipeItem("stock", "4 cups"), RecipeItem("eggs", "2, beaten"),
                       RecipeItem("scallion", "2, sliced"), RecipeItem("ginger", "1 tsp"),
                       RecipeItem("soy_sauce", "1 tbsp"), RecipeItem("corn", "1/2 cup")],
               steps: ["Bring the stock to a simmer with the ginger and soy sauce.",
                       "Add the corn and cook 2 minutes.",
                       "Swirl the broth and pour in the beaten egg in a thin stream.",
                       "Turn off the heat and scatter with scallions."],
               tip: "Pour the egg slowly while stirring — that's what makes the ribbons."),

        Recipe(id: "hummus_plate", name: "Lemon Hummus Plate",
               blurb: "Bright homemade hummus with warm bread.",
               kind: .snack, minutes: 10, servings: 3, difficulty: .easy,
               items: [RecipeItem("chickpeas", "1 can"), RecipeItem("lemon", "1"),
                       RecipeItem("garlic", "1 clove"), RecipeItem("olive_oil", "3 tbsp"),
                       RecipeItem("cumin", "1/2 tsp"), RecipeItem("bread", "to serve"),
                       RecipeItem("salt", "to taste")],
               steps: ["Blend the chickpeas with lemon juice, garlic, cumin, and salt.",
                       "Stream in the olive oil until smooth and creamy.",
                       "Loosen with a little cold water if needed.",
                       "Swirl onto a plate, drizzle with oil, and serve with warm bread."],
               tip: "A few ice-cold tablespoons of water make hummus dramatically fluffier."),

        Recipe(id: "baked_feta_pasta", name: "Baked Feta Pasta",
               blurb: "The oven does the sauce — feta and burst tomatoes.",
               kind: .dinner, minutes: 35, servings: 3, difficulty: .easy,
               items: [RecipeItem("pasta", "300 g"), RecipeItem("feta", "1 block"),
                       RecipeItem("tomato", "3 cups cherry or chopped"), RecipeItem("garlic", "3 cloves"),
                       RecipeItem("olive_oil", "3 tbsp"), RecipeItem("chili_flakes", "a pinch"),
                       RecipeItem("basil", "a handful")],
               steps: ["Heat the oven to 200°C (400°F).",
                       "Put the feta in the middle of a baking dish, surround with tomatoes, oil, and garlic.",
                       "Bake 25 minutes until the tomatoes burst and the feta softens.",
                       "Mash into a sauce, toss with cooked pasta, and finish with basil and chili flakes."],
               tip: "Save a cup of pasta water — the sauce loves a starchy splash."),

        Recipe(id: "yogurt_parfait", name: "Honey Yogurt Parfait",
               blurb: "Layers of yogurt, berries, and toasted oats.",
               kind: .breakfast, minutes: 5, servings: 1, difficulty: .easy,
               items: [RecipeItem("yogurt", "1 cup"), RecipeItem("mixed_berries", "1/2 cup"),
                       RecipeItem("oats", "1/4 cup"), RecipeItem("honey", "1 tbsp")],
               steps: ["Toast the oats in a dry pan until golden and nutty.",
                       "Layer yogurt, berries, and oats in a glass.",
                       "Drizzle with honey and serve."],
               tip: "Toasting the oats takes two minutes and changes everything."),

        Recipe(id: "croque_monsieur", name: "Croque Monsieur",
               blurb: "The Parisian café sandwich with creamy sauce.",
               kind: .lunch, minutes: 20, servings: 2, difficulty: .medium,
               items: [RecipeItem("bread", "4 slices"), RecipeItem("ham", "4 slices"),
                       RecipeItem("cheddar", "1 cup, grated"), RecipeItem("butter", "2 tbsp"),
                       RecipeItem("flour", "1 tbsp"), RecipeItem("milk", "3/4 cup")],
               steps: ["Melt the butter, stir in the flour, then whisk in the milk to a smooth sauce.",
                       "Stir half the cheese into the sauce.",
                       "Layer ham and a spoon of sauce between the bread slices.",
                       "Top with the rest of the sauce and cheese and grill until golden and bubbling."],
               tip: "The sauce on top — not inside — is what makes it a true croque."),

        Recipe(id: "classic_crepes", name: "Paper Thin Crepes",
               blurb: "Delicate French crepes for sweet fillings.",
               kind: .dessert, minutes: 25, servings: 3, difficulty: .medium,
               items: [RecipeItem("flour", "1 cup"), RecipeItem("eggs", "2"),
                       RecipeItem("milk", "1.5 cups"), RecipeItem("butter", "2 tbsp, melted"),
                       RecipeItem("sugar", "1 tbsp")],
               steps: ["Whisk everything into a thin, lump-free batter and rest it 10 minutes.",
                       "Heat a lightly buttered pan over medium heat.",
                       "Pour in a small ladle and swirl to coat the pan thinly.",
                       "Cook until lacy at the edges, flip, and give it 20 more seconds.",
                       "Stack and fill with whatever you love."],
               tip: "The first crepe is always a sacrifice to the pan. That's the rule."),

        Recipe(id: "french_onion_soup", name: "French Onion Soup",
               blurb: "Deeply caramelised onions under a cheesy lid.",
               kind: .soup, minutes: 50, servings: 3, difficulty: .medium,
               items: [RecipeItem("onion", "4, thin sliced"), RecipeItem("butter", "3 tbsp"),
                       RecipeItem("stock", "5 cups"), RecipeItem("bread", "3 slices"),
                       RecipeItem("cheddar", "1 cup, grated"), RecipeItem("thyme", "1 tsp"),
                       RecipeItem("salt", "to taste")],
               steps: ["Cook the onions in butter low and slow for 25–30 minutes until deep amber.",
                       "Add the thyme and stock and simmer 15 minutes.",
                       "Ladle into bowls and float a slice of toasted bread on each.",
                       "Pile on the cheese and grill until molten and golden."],
               tip: "The color of the onions is the flavor of the soup — don't rush them."),

        Recipe(id: "chicken_fajitas", name: "Sizzling Chicken Fajitas",
               blurb: "Charred peppers and spiced chicken, build-your-own.",
               kind: .dinner, minutes: 25, servings: 3, difficulty: .easy,
               items: [RecipeItem("chicken", "2 breasts, sliced"), RecipeItem("bell_pepper", "2, sliced"),
                       RecipeItem("onion", "1, sliced"), RecipeItem("tortilla", "6 small"),
                       RecipeItem("lime", "1"), RecipeItem("paprika", "1 tsp"),
                       RecipeItem("cumin", "1 tsp"), RecipeItem("veg_oil", "2 tbsp")],
               steps: ["Toss the chicken with the paprika, cumin, and half the oil.",
                       "Sear in a screaming-hot pan until charred, then set aside.",
                       "Char the peppers and onion in the same pan.",
                       "Return the chicken, squeeze over the lime, and serve with warm tortillas."],
               tip: "A very hot pan and no crowding — char is the whole point of fajitas."),

        Recipe(id: "burrito_bowl", name: "Veggie Burrito Bowl",
               blurb: "All the burrito, none of the wrapping skills.",
               kind: .lunch, minutes: 25, servings: 2, difficulty: .easy,
               items: [RecipeItem("rice", "1 cup"), RecipeItem("black_beans", "1 can"),
                       RecipeItem("corn", "1/2 cup"), RecipeItem("tomato", "1, diced"),
                       RecipeItem("avocado", "1, sliced"), RecipeItem("lime", "1"),
                       RecipeItem("cilantro", "a handful"), RecipeItem("cumin", "1 tsp")],
               steps: ["Cook the rice and fold in the lime zest and half the juice.",
                       "Warm the beans with the cumin.",
                       "Build bowls: rice, beans, corn, tomato, and avocado.",
                       "Finish with cilantro and the rest of the lime."],
               tip: "Lime rice is the quiet hero — don't skip zesting."),

        Recipe(id: "pico_de_gallo", name: "Pico de Gallo",
               blurb: "Fresh chopped salsa in ten minutes flat.",
               kind: .snack, minutes: 10, servings: 4, difficulty: .easy,
               items: [RecipeItem("tomato", "3, diced fine"), RecipeItem("onion", "1/2, minced"),
                       RecipeItem("cilantro", "a big handful"), RecipeItem("lime", "1"),
                       RecipeItem("salt", "to taste")],
               steps: ["Dice the tomatoes small and mince the onion.",
                       "Chop the cilantro and combine everything.",
                       "Season with lime juice and salt.",
                       "Rest 10 minutes so the juices mingle."],
               tip: "Salt draws out the tomato juice — that liquid is the dressing."),

        Recipe(id: "skillet_flatbread_pizza", name: "Skillet Flatbread Pizza",
               blurb: "No yeast, no oven drama — pizza from a pan.",
               kind: .dinner, minutes: 30, servings: 2, difficulty: .medium,
               items: [RecipeItem("flour", "1.5 cups"), RecipeItem("baking_powder", "2 tsp"),
                       RecipeItem("yogurt", "1 cup"), RecipeItem("tomato_paste", "3 tbsp"),
                       RecipeItem("mozzarella", "1 cup"), RecipeItem("basil", "a handful"),
                       RecipeItem("olive_oil", "1 tbsp"), RecipeItem("salt", "1/2 tsp")],
               steps: ["Mix the flour, baking powder, salt, and yogurt into a soft dough.",
                       "Divide and roll into two thin rounds.",
                       "Cook each in an oiled pan until bubbly underneath.",
                       "Flip, spread with tomato paste, scatter cheese, and cover until melted.",
                       "Finish with basil."],
               tip: "Two-ingredient yogurt dough puffs beautifully in a hot pan."),

        Recipe(id: "bruschetta", name: "Tomato Basil Bruschetta",
               blurb: "Garlic-rubbed toast piled with marinated tomatoes.",
               kind: .snack, minutes: 12, servings: 3, difficulty: .easy,
               items: [RecipeItem("bread", "6 slices"), RecipeItem("tomato", "3, diced"),
                       RecipeItem("basil", "a handful"), RecipeItem("garlic", "2 cloves"),
                       RecipeItem("olive_oil", "3 tbsp"), RecipeItem("salt", "to taste")],
               steps: ["Toss the tomatoes with torn basil, olive oil, and salt; rest 5 minutes.",
                       "Toast the bread until deeply golden.",
                       "Rub each slice with a cut garlic clove while hot.",
                       "Pile on the tomatoes and their juices."],
               tip: "Rubbing raw garlic on hot toast beats mixing it in — gentler and more aromatic."),

        Recipe(id: "coconut_noodle_soup", name: "Coconut Curry Noodle Soup",
               blurb: "A fragrant, warming bowl with a gentle kick.",
               kind: .soup, minutes: 25, servings: 2, difficulty: .medium,
               items: [RecipeItem("coconut_milk", "1 can"), RecipeItem("stock", "2 cups"),
                       RecipeItem("noodles", "150 g"), RecipeItem("mushroom", "1 cup, sliced"),
                       RecipeItem("ginger", "1 tbsp"), RecipeItem("curry_powder", "1 tbsp"),
                       RecipeItem("lime", "1/2"), RecipeItem("cilantro", "to serve")],
               steps: ["Toast the curry powder and ginger in a dry pot for 30 seconds.",
                       "Add the coconut milk and stock and bring to a simmer.",
                       "Add the mushrooms and noodles and cook until tender.",
                       "Finish with lime juice and cilantro."],
               tip: "Add the lime off the heat — it stays bright instead of turning bitter."),
    ]

    static let recipeByID: [String: Recipe] = {
        Dictionary(uniqueKeysWithValues: recipes.map { ($0.id, $0) })
    }()

    // MARK: - Cuisines

    static let cuisineByRecipe: [String: Cuisine] = [
        // Italian
        "tomato_garlic_pasta": .italian, "caprese_salad": .italian,
        "spaghetti_bolognese": .italian, "veggie_frittata": .italian,
        "shrimp_garlic_pasta": .italian, "minestrone": .italian,
        "mushroom_rice": .italian, "sausage_pasta": .italian,
        "skillet_flatbread_pizza": .italian, "bruschetta": .italian,
        // French
        "classic_omelette": .french, "french_toast": .french,
        "beef_stew": .french, "ham_cheese_melt": .french,
        "ratatouille": .french, "croque_monsieur": .french,
        "classic_crepes": .french, "french_onion_soup": .french,
        // Mediterranean
        "lentil_soup": .mediterranean, "greek_salad": .mediterranean,
        "baked_salmon": .mediterranean, "stuffed_peppers": .mediterranean,
        "roast_veggies": .mediterranean, "citrus_fruit_salad": .mediterranean,
        "garden_veg_soup": .mediterranean, "shakshuka": .mediterranean,
        "hummus_plate": .mediterranean, "baked_feta_pasta": .mediterranean,
        "yogurt_parfait": .mediterranean,
        // Mexican
        "black_bean_tacos": .mexican, "beef_chili": .mexican,
        "cheese_quesadilla": .mexican, "guacamole": .mexican,
        "chicken_fajitas": .mexican, "burrito_bowl": .mexican,
        "pico_de_gallo": .mexican,
        // Asian
        "veggie_fried_rice": .asian, "chicken_stir_fry": .asian,
        "peanut_noodles": .asian, "chicken_rice_bowl": .asian,
        "cucumber_salad": .asian, "tofu_stir_fry": .asian,
        "honey_garlic_pork": .asian, "teriyaki_chicken": .asian,
        "soy_ginger_noodles": .asian, "egg_drop_soup": .asian,
        "coconut_noodle_soup": .asian,
        // Indian
        "chickpea_curry": .indian, "golden_lentil_dal": .indian,
        "spiced_potato_curry": .indian, "coconut_veggie_curry": .indian,
        // American
        "avocado_toast": .american, "grilled_cheese": .american,
        "banana_pancakes": .american, "tomato_soup": .american,
        "chicken_noodle_soup": .american, "scrambled_eggs": .american,
        "mashed_potatoes": .american, "tuna_melt": .american,
        "oatmeal_bowl": .american, "potato_hash": .american,
        "berry_smoothie": .american, "banana_bread": .american,
        "coleslaw": .american, "bacon_egg_sandwich": .american,
        "garden_wrap": .american, "apple_crumble": .american,
    ]

    static func recipes(in cuisine: Cuisine) -> [Recipe] {
        recipes.filter { $0.cuisine == cuisine }
    }

    // Meat and fish — used to derive the vegetarian flag.
    static let meatAndFishIDs: Set<String> = [
        "chicken", "beef", "ground_beef", "pork", "bacon",
        "sausage", "ham", "shrimp", "salmon", "tuna",
    ]

    // MARK: - Collections (Discover shelves)

    static let collections: [RecipeCollection] = [
        RecipeCollection(id: "quick", title: "Quick & Easy",
                         subtitle: "On the table in 20 minutes",
                         glyph: .clock, tint: Kitchen.accent,
                         matches: { $0.isQuick && $0.difficulty == .easy }),
        RecipeCollection(id: "veggie", title: "Vegetarian",
                         subtitle: "No meat, all flavor",
                         glyph: .leaf, tint: Kitchen.grpVeg,
                         matches: { $0.isVegetarian }),
        RecipeCollection(id: "cozy", title: "Soups & Stews",
                         subtitle: "Warm bowls for slow days",
                         glyph: .bowl, tint: Kitchen.grpProtein,
                         matches: { $0.kind == .soup || $0.id == "beef_stew" }),
        RecipeCollection(id: "few", title: "Few Ingredients",
                         subtitle: "Six items or fewer",
                         glyph: .basket, tint: Kitchen.honey,
                         matches: { $0.items.count <= 6 }),
        RecipeCollection(id: "morning", title: "Breakfast Club",
                         subtitle: "Start the day right",
                         glyph: .sunrise, tint: Kitchen.grpFruit,
                         matches: { $0.kind == .breakfast }),
        RecipeCollection(id: "sweet", title: "Sweet Treats",
                         subtitle: "Desserts & drinks",
                         glyph: .cake, tint: Kitchen.grpDairy,
                         matches: { $0.kind == .dessert || $0.kind == .drink }),
    ]
}
